import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const VERDICT_TAG = {
    成格: "tag-good",
    成: "tag-good",
    救应: "tag-neutral",
    败格: "tag-bad",
    败: "tag-bad",
};
export function DiagnosisPanel({ diagnosis }) {
    const { yong_shen, ge_ju, xiang_shen, cheng_bai } = diagnosis;
    return (_jsxs("div", { className: "card", children: [_jsx("div", { className: "card-header", children: _jsxs("div", { className: "card-title", children: ["DIAGNOSIS ", _jsx("span", { className: "cn", children: "\u6838\u5FC3\u8BCA\u65AD" })] }) }), _jsxs("div", { style: { padding: 0 }, children: [_jsxs("div", { className: "diag-cell", children: [_jsx("div", { className: "diag-label", children: "DAY MASTER \u65E5\u4E3B" }), _jsxs("div", { className: "diag-value", children: [diagnosis.day_master, _jsx("span", { className: `tag ${diagnosis.chart_summary.includes("身弱") ? "tag-bad" : "tag-good"}`, children: diagnosis.chart_summary.includes("身弱") ? "身弱" : "身强" })] })] }), _jsxs("div", { className: "diag-cell", children: [_jsx("div", { className: "diag-label", children: "YONG SHEN \u7528\u795E" }), _jsx("div", { className: "diag-gods", children: _jsxs("span", { className: "god-chip yong", children: [yong_shen.stem, " \u00B7 ", yong_shen.ten_god] }) })] }), xiang_shen.xiang_shen.length > 0 && (_jsxs("div", { className: "diag-cell", children: [_jsx("div", { className: "diag-label", children: "XIANG SHEN \u76F8\u795E" }), _jsx("div", { className: "diag-gods", children: xiang_shen.xiang_shen.map((x, i) => (_jsxs("span", { className: "god-chip xiang", children: [x.stem, " \u00B7 ", x.ten_god] }, i))) })] })), xiang_shen.ji_shen.length > 0 && (_jsxs("div", { className: "diag-cell", children: [_jsx("div", { className: "diag-label", children: "JI SHEN \u5FCC\u795E" }), _jsx("div", { className: "diag-gods", children: xiang_shen.ji_shen.map((x, i) => (_jsxs("span", { className: "god-chip ji", children: [x.stem, " \u00B7 ", x.ten_god] }, i))) })] })), _jsxs("div", { className: "diag-cell", children: [_jsx("div", { className: "diag-label", children: "GE JU \u683C\u5C40" }), _jsxs("div", { className: "diag-value", children: [ge_ju.name, !ge_ju.unresolved && (_jsx("span", { className: `tag ${VERDICT_TAG[cheng_bai.verdict] || "tag-good"}`, children: cheng_bai.verdict }))] })] }), _jsxs("div", { className: "diag-cell", children: [_jsx("div", { className: "diag-label", children: "CHENG BAI \u6210\u8D25" }), _jsxs("div", { className: "diag-value", children: [cheng_bai.verdict, cheng_bai.rescue_gods.length > 0 && (_jsxs("span", { className: "tag tag-good", children: [cheng_bai.rescue_gods.map((g) => g.stem).join(""), "\u62A4"] }))] })] })] })] }));
}
